apiVersion: v1
kind: Pod
metadata:
  name: run-reporter
  namespace: calico-monitoring
  labels:
    k8s-app: compliance-reporter
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccountName: tigera-compliance-reporter
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  imagePullSecrets:
    - name: cnx-pull-secret
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup elasticsearch-tigera-elasticsearch.calico-monitoring.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']
  containers:
  - name: reporter
    # Modify this image name, if you have re-tagged the image and are using a local
    # docker image repository.
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    image: quay.io/tigera/compliance-reporter:v2.4.0
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    env:
      # Modify these values with the report name and start and end time of the report
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: TIGERA_COMPLIANCE_REPORT_NAME
      value: policy-audit-report
    - name: TIGERA_COMPLIANCE_REPORT_START_TIME
      value: "2019-05-09T00:00:15Z"
      #- name: TIGERA_COMPLIANCE_REPORT_END_TIME
      #value: "2019-05-10T01:42:15Z"
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: LOG_LEVEL
      value: "warning"
    - name: ELASTIC_INDEX_SUFFIX
      valueFrom:
        configMapKeyRef:
          name: tigera-es-config
          key: tigera.elasticsearch.cluster-name
    - name: ELASTIC_SCHEME
      valueFrom:
        configMapKeyRef:
          name: tigera-es-config
          key: tigera.elasticsearch.scheme
          optional: true
    - name: ELASTIC_HOST
      valueFrom:
        configMapKeyRef:
          name: tigera-es-config
          key: tigera.elasticsearch.host
    - name: ELASTIC_PORT
      valueFrom:
        configMapKeyRef:
          name: tigera-es-config
          key: tigera.elasticsearch.port
          optional: true
    - name: ELASTIC_USER
      valueFrom:
        secretKeyRef:
          name: elastic-compliance-user
          key: reporter.username
          optional: true
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elastic-compliance-user
          key: reporter.password
          optional: true
    - name: ELASTIC_SSL_VERIFY
      value: "true"
    - name: ELASTIC_CA
      valueFrom:
        configMapKeyRef:
          name: tigera-es-config
          key: tigera.elasticsearch.ca.path
          optional: true
    volumeMounts:
    - name: elastic-ca-cert-volume
      mountPath: /etc/ssl/elastic/
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9099
        host: localhost
  volumes:
  - name: elastic-ca-cert-volume
    secret:
      optional: true
      items:
      - key: tigera.elasticsearch.ca
        path: ca.pem
      secretName: tigera-es-config

